repositories {
    mavenLocal()
    mavenCentral()
    maven {
        name = 'Kotlin for Forge'
        url = 'https://thedarkcolour.github.io/KotlinForForge/'
        content { includeGroup "thedarkcolour" }
    }
    maven { // Anvil Lib
        name = "Cjsah Maven"
        url = "https://server.cjsah.net:1002/maven/"
        content {
            includeGroup "dev.anvilcraft.lib"
            includeGroup "dev.dubhe"
            // 藿香（Ageratum，AnvilCraft 的手册 mod）
            includeGroup "dev.anvilcraft.resource"
        }
    }
    maven { // Registrate Fork
        name = "Ithundxr Maven"
        url = "https://maven.ithundxr.dev/snapshots"
        content {
            includeGroup "com.tterrag.registrate"
        }
    }
    maven { // JEI（编译期用，写 JEI 伪配方展示）
        name = "BlameJared"
        url = "https://maven.blamejared.com"
        content {
            includeGroup "mezz.jei"
        }
    }
}
